config/routes.rb
Rails.application.routes.draw do
  get 'simple_pages/index'
  get 'simple_pages/faq'
  get 'simple_pages/contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def faq
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deckhand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path%></li>
        <li><%= link_to "FAQ", simple_pages_faq_path%></li>
        <li><%= link_to "Contact", simple_pages_contact_path%></li>
      </ul>
    </nav>

    <%= yield %>

    <footer>
      &copy; 2017 Deckhand
    </footer>
  </body>
</html>

app/views/simple_pages/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/simple_pages/contact.html.erb</p>

app/views/simple_pages/faq.html.erb
<h1>FAQ</h1>
<p>Check here first if you have a question. It may have already been answered.</p>

app/views/simple_pages/index.html.erb
<h1>All Products</h1>